apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-frontend
  template:
    metadata:
      labels:
        app: trend-frontend
    spec:
      containers:
      - name: trend-frontend
        image: amritapl/trend-frontend:latest
        ports:
        - containerPort: 80
